[data]
url = 'https://nicholas.carlini.com/writing/2019/advex_papers.json'
author = 'Nicholas Carlini'

[days]
daily = 1
weekly = 7
biweekly = 14

[rss]
title = 'Adversarial Example Papers'
link = 'https://nicholas.carlini.com/writing/2019/all-adversarial-example-papers.html'
description = 'Adversarial example papers collected by Nicholas Carlini.'
language = 'en-us'
generator = 'advex-papers-rss'
